In [ ]:
from openravepy import *
import openravepy

In [ ]:
openravepy.__file__

In [ ]:
env = Environment()

In [ ]:
 # create openrave environment
env.SetViewer('qtcoin') # attach viewer (optional)
env.Load('/home/liquanlin/workspace/catkin_ws/src/x_arm/robots/x_arm_openrave.xml') # load a simple scene
robot = env.GetRobots()[0] # get the first robot
calib = env.GetRobots()[1] # get the first robot

In [ ]:
with env: # lock the environment since robot will be used
    raveLogInfo("Robot "+robot.GetName()+" has "+repr(robot.GetDOF())+" joints with values:\n"+repr(robot.GetDOFValues()))
    #robot.SetDOFValues([0.5],[1]) # set joint 0 to value 
    robot.SetDOFValues([0,0,0,1.57,0,0,0],[0,1,2,3,4,5,6]) # set joint 0 to value
    N = 9
    T = robot.GetLinks()[N].GetTransform() # get the transform of link 1
    print T
    raveLogInfo("The transformation of link 1 is:\n"+repr(T))
    print robot.GetLinks()[11].GetName

In [ ]:
import tf
tf.transformations.quaternion_from_matrix(T)

In [ ]:
with env: # lock the environment since robot will be used
    raveLogInfo("Robot "+calib.GetName()+" has "+repr(calib.GetDOF())+" joints with values:\n"+repr(calib.GetDOFValues()))
    #robot.SetDOFValues([0.5],[1]) # set joint 0 to value 
    calib.SetDOFValues([0,0,0,1.57,0,0,0],[0,1,2,3,4,5,6]) # set joint 0 to value
    M = 9
    Tc = calib.GetLinks()[M].GetTransform() # get the transform of link 1
    print Tc
    raveLogInfo("The transformation of link 1 is:\n"+repr(Tc))
    print calib.GetLinks()[11].GetName

In [ ]:
tf.transformations.quaternion_from_matrix(Tc)

In [ ]:
RaveSetDebugLevel(DebugLevel.Debug) # set output level to debug

manipprob = interfaces.BaseManipulation(robot) # create the interface for basic manipulation programs
manipprob.MoveManipulator(goal=[1.5707963,0,0,0,0,0,0]) # call motion planner with goal joint angles
robot.WaitForController(0) # wait

In [ ]:
manipprob.MoveManipulator(goal=[0,1.24,-0.064,1,-1.16,-1.548,1.0]) # call motion planner with goal joint angles
robot.WaitForController(0) # wait

In [1]:
import h5py
fileName = "/home/liquanlin/workspace/catkin_ws/src/x_arm/robots/reachability.23dac63c4f1c2dae013c3a123f525e6f.pp"
f=h5py.File(fileName,'r')

In [2]:
reachabilitystats = f['reachabilitystats']
reachabilitydensity3d = f['reachabilitydensity3d']
reachability3d = f['reachability3d']
pointscale = f['pointscale'].value
xyzdelta = f['xyzdelta'].value
quatdelta = f['quatdelta'].value

In [3]:
reachabilitystats[10675002+10,:]

array([-0.24852581, -0.32388514,  0.88176561, -0.23626838, -0.03      ,
        0.02      ,  0.54      ,  1.        ])

In [4]:
reachabilitydensity3d

<HDF5 dataset "reachabilitydensity3d": shape (136, 136, 136), type "<f8">

In [5]:
reachability3d

<HDF5 dataset "reachability3d": shape (136, 136, 136), type "<f8">

In [6]:
import numpy as np
center = 68
len = reachabilitystats.maxshape[0]
poseSolutionsIndexInSerialization = np.zeros([center*2+1,center*2+1,center*2+1,2])
reachabilitySet =np.zeros([len,4])
len

26613696

In [7]:
for i in range(len):
    x = int(reachabilitystats[i,4]*100 + center)
    y = int(reachabilitystats[i,5]*100 + center)
    z = int(reachabilitystats[i,6]*100 + center)
    if poseSolutionsIndexInSerialization[x,y,z,0]<1:
        poseSolutionsIndexInSerialization[x,y,z,1] = i #start position in the reachability set of point(x,y,z) 
    poseSolutionsIndexInSerialization[x,y,z,0] += 1    #num of solutions
    reachabilitySet[i,0:4] = reachabilitystats[i,0:4]  #quaterion
    if i%10000 == 0:
        print i;

0
10000
20000
30000
40000
50000
60000
70000
80000
90000
100000
110000
120000
130000
140000
150000
160000
170000
180000
190000
200000
210000
220000
230000
240000
250000
260000
270000
280000
290000
300000
310000
320000
330000
340000
350000
360000
370000
380000
390000
400000
410000
420000
430000
440000
450000
460000
470000
480000
490000
500000
510000
520000
530000
540000
550000
560000
570000
580000
590000
600000
610000
620000
630000
640000
650000
660000
670000
680000
690000
700000
710000
720000
730000
740000
750000
760000
770000
780000
790000
800000
810000
820000
830000
840000
850000
860000
870000
880000
890000
900000
910000
920000
930000
940000
950000
960000
970000
980000
990000
1000000
1010000
1020000
1030000
1040000
1050000
1060000
1070000
1080000
1090000
1100000
1110000
1120000
1130000
1140000
1150000
1160000
1170000
1180000
1190000
1200000
1210000
1220000
1230000
1240000
1250000
1260000
1270000
1280000
1290000
1300000
1310000
1320000
1330000
1340000
1350000
1360000
1370000
1380000
13

10350000
10360000
10370000
10380000
10390000
10400000
10410000
10420000
10430000
10440000
10450000
10460000
10470000
10480000
10490000
10500000
10510000
10520000
10530000
10540000
10550000
10560000
10570000
10580000
10590000
10600000
10610000
10620000
10630000
10640000
10650000
10660000
10670000
10680000
10690000
10700000
10710000
10720000
10730000
10740000
10750000
10760000
10770000
10780000
10790000
10800000
10810000
10820000
10830000
10840000
10850000
10860000
10870000
10880000
10890000
10900000
10910000
10920000
10930000
10940000
10950000
10960000
10970000
10980000
10990000
11000000
11010000
11020000
11030000
11040000
11050000
11060000
11070000
11080000
11090000
11100000
11110000
11120000
11130000
11140000
11150000
11160000
11170000
11180000
11190000
11200000
11210000
11220000
11230000
11240000
11250000
11260000
11270000
11280000
11290000
11300000
11310000
11320000
11330000
11340000
11350000
11360000
11370000
11380000
11390000
11400000
11410000
11420000
11430000
11440000
11450000
1

19460000
19470000
19480000
19490000
19500000
19510000
19520000
19530000
19540000
19550000
19560000
19570000
19580000
19590000
19600000
19610000
19620000
19630000
19640000
19650000
19660000
19670000
19680000
19690000
19700000
19710000
19720000
19730000
19740000
19750000
19760000
19770000
19780000
19790000
19800000
19810000
19820000
19830000
19840000
19850000
19860000
19870000
19880000
19890000
19900000
19910000
19920000
19930000
19940000
19950000
19960000
19970000
19980000
19990000
20000000
20010000
20020000
20030000
20040000
20050000
20060000
20070000
20080000
20090000
20100000
20110000
20120000
20130000
20140000
20150000
20160000
20170000
20180000
20190000
20200000
20210000
20220000
20230000
20240000
20250000
20260000
20270000
20280000
20290000
20300000
20310000
20320000
20330000
20340000
20350000
20360000
20370000
20380000
20390000
20400000
20410000
20420000
20430000
20440000
20450000
20460000
20470000
20480000
20490000
20500000
20510000
20520000
20530000
20540000
20550000
20560000
2

In [ ]:
h5f = h5py.File('pose-1364698_576_4_20190222.h5', 'w')
h5f.create_dataset('poseSolutionsIndexInSerialization', data=poseSolutionsIndexInSerialization)
h5f.create_dataset('reachabilitySet', data=reachabilitySet)
h5f.create_dataset('center', data=center)
h5f.close()

In [ ]:
#import h5py
#h5f = h5py.File('pose-1364698_576.h5', 'r')
#poseSolutionsIndexInSerialization = h5f['poseSolutionsIndexInSerialization']
#reachabilitySet = h5f['reachabilitySet']
#center = h5f['center']

In [7]:
import h5py
h5f = h5py.File('pose-1364698_576_4.h5', 'r')
poseSolutionsIndexInSerialization = h5f['poseSolutionsIndexInSerialization']
reachabilitySet = h5f['reachabilitySet']
center = h5f['center']

In [8]:
poseSolutionsIndexInSerialization[68,68,118,:]

array([  5.80000000e+01,   6.53677800e+06])

In [9]:
reachabilitySet[6536778:6536778+33,:]

array([[  8.09511339e-01,  -1.06574190e-01,  -3.51468575e-01,
          4.58042765e-01],
       [  6.47770290e-01,  -4.97051625e-01,  -5.72410958e-01,
         -7.53593322e-02],
       [  7.54344479e-01,  -3.12459714e-01,  -5.33402097e-01,
         -2.20942383e-01],
       [  8.43382767e-01,  -3.49340580e-01,  -4.08248290e-01,
          9.87294620e-17],
       [ -7.53593322e-02,   5.72410958e-01,  -1.06574190e-01,
          8.09511339e-01],
       [  9.22959556e-02,   7.01057385e-01,  -1.83012702e-01,
          6.83012702e-01],
       [ -9.22959556e-02,   7.01057385e-01,  -3.53553391e-01,
          6.12372436e-01],
       [ -1.06574190e-01,   8.09511339e-01,  -7.53593322e-02,
          5.72410958e-01],
       [  5.72410958e-01,   7.53593322e-02,  -1.06574190e-01,
          8.09511339e-01],
       [  5.33402097e-01,   2.20942383e-01,  -3.12459714e-01,
          7.54344479e-01],
       [  4.58042765e-01,   3.51468575e-01,  -4.97051625e-01,
          6.47770290e-01],
       [ -3.51468575e

In [ ]:
pointsInSerial = np.zeros([137*137*137,4])
m=0;
for i in range(137):
    for j in range(137):
        for k in range(137):
            pointsInSerial[i*137*137+j*137+k,0] = (i-center.value)/100.0
            pointsInSerial[i*137*137+j*137+k,1] = (j-center.value)/100.0
            pointsInSerial[i*137*137+j*137+k,2] = (k-center.value)/100.0
            pointsInSerial[i*137*137+j*137+k,3] = poseSolutionsIndexInSerialization[i,j,k,0]
            m=m+1
            if m%10000 == 0:
                print m
np.savetxt('pose.txt', pointsInSerial, delimiter=' ',fmt='%1.2e',newline='\n') 

In [10]:
import time
import openravepy
if not __openravepy_build_doc__:
    from openravepy import *
    from numpy import *
env = Environment()
env.SetViewer('qtcoin') # attach viewer (optional)
env.Load('/home/liquanlin/workspace/catkin_ws/src/x_arm/robots/x_arm.xml')
robot = env.GetRobots()[0]
x_arm = robot.SetActiveManipulator("x_arm")



for link in robot.GetLinks():
    for geom in link.GetGeometries():
        geom.SetTransparency(0.1)
    
newrobots = []
for ind in range(49):
    newrobot = RaveCreateRobot(env,robot.GetXMLId())
    newrobot.Clone(robot,0)
    for link in newrobot.GetLinks():
        for geom in link.GetGeometries():
            geom.SetTransparency(0.7)
    newrobots.append(newrobot)

ikmodel = databases.inversekinematics.InverseKinematicsModel(robot, iktype=IkParameterization.Type.Transform6D)
if not ikmodel.load():
    ikmodel.autogenerate()
    
T = eye(4)

In [ ]:
N = 8
with env:
# move the robot in a random collision-free position and call the IK

    for j in range(10):
        #while True:
#        lower,upper = [v[ikmodel.manip.GetArmIndices()] for v in ikmodel.robot.GetDOFLimits()]
#        robot.SetDOFValues(random.rand()*(upper-lower)+lower,ikmodel.manip.GetArmIndices()) # set random values
#            if not robot.CheckSelfCollision():
#            solutions = ikmodel.manip.FindIKSolutions(ikmodel.manip.GetTransform(),IkFilterOptions.CheckEnvCollisions)
        T = matrixFromQuat(reachabilitySet[6536778+j,:])
        T[0:3,3] = [0,0,0.5]
        solutions = ikmodel.manip.FindIKSolutions(T,0)
                #print solutions[1,:]
#                print solutions.shape
#                print type(solutions)
                #if solutions is not None and len(solutions) > 0: # if found, then break
#        break
                
            
#        print 'found %d solutions, rendering solutions:'%len(solutions)
#        if len(solutions) < 10:
#            inds = range(len(solutions))
#        else:
#            inds = array(linspace(0,len(solutions)-1,10),int)
#        for i,ind in enumerate(inds):
#            print ind
        if len(solutions) > 0:
            print len(solutions)
            if j<N:
                newrobot = newrobots[j]
                env.Add(newrobot,True)
                newrobot.SetTransform(robot.GetTransform())
                newrobot.SetDOFValues(solutions[0],ikmodel.manip.GetArmIndices())
            
            if j==N:
                robot.SetDOFValues(solutions[0],ikmodel.manip.GetArmIndices())
            
            if j>N:
                newrobot = newrobots[j+1]
                env.Add(newrobot,True)
                newrobot.SetTransform(robot.GetTransform())
                newrobot.SetDOFValues(solutions[0],ikmodel.manip.GetArmIndices())
        print len(solutions)
            
            
env.UpdatePublishedBodies()
print('waiting...')
time.sleep(100)
# remove the robots
for newrobot in newrobots:
    env.Remove(newrobot)

11
11
5
5
4
4
7
7
6
6
0
0
0
8
8
12
12
waiting...


In [ ]:
T = matrixFromQuat([-2.66435474e-02,   2.02377835e-01,   7.76649294e-01, -5.95943963e-01])
T[0:3,3] = [0.22,0.22,  0.22]
solutions = ikmodel.manip.FindIKSolutions(T,IkFilterOptions.CheckEnvCollisions)
solutions

In [ ]:
newrobot = newrobots[0]
env.Add(newrobot,True)
newrobot.SetTransform(robot.GetTransform())
newrobot.SetDOFValues(solutions[0],ikmodel.manip.GetArmIndices())

In [ ]:
env.UpdatePublishedBodies()

In [ ]:
solutions